/* Generated By:JavaCC: Do not edit this line. Sql.java */
package edu.buffalo.cse.sql;

import java.util.Map;
import java.util.List;
import java.io.File;
import edu.buffalo.cse.sql.Schema;
import edu.buffalo.cse.sql.data.Datum;
import edu.buffalo.cse.sql.plan.PlanNode;

public class Sql {

  public static void main( String[] args )
  {
    System.out.println("You haven't implemented me yet!");
  }

  public static List<Datum[]> execQuery(
      Map<String, Schema.TableFromFile> tables,
      PlanNode q
    )
    throws SqlException
    { throw new SqlException("execQuery() is unimplemented"); }

  public static List<List<Datum[]>> execFile(
      File program
    )
    throws SqlException
    { throw new SqlException("execQuery() is unimplemented"); }
}